# Generated by Django 5.0.2 on 2024-02-17 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('totembo', '0003_product_strap_watch'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='strap_watch',
            new_name='type_watch',
        ),
    ]
