# Generated by Django 5.0.2 on 2024-02-17 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('totembo', '0005_addproductdescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdescription',
            name='parameter_info',
            field=models.TextField(blank=True, max_length=400, null=True, verbose_name='Описание параметра'),
        ),
    ]
