# Generated by Django 5.0.2 on 2024-02-17 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('totembo', '0006_alter_productdescription_parameter_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='desc',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Название описания'),
        ),
        migrations.AddField(
            model_name='product',
            name='full_title',
            field=models.TextField(blank=True, null=True, verbose_name='Полное описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='add_product_description/', verbose_name='Картинка к описанию'),
        ),
        migrations.DeleteModel(
            name='AddProductDescription',
        ),
    ]
