# Generated by Django 5.0.2 on 2024-02-19 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('totembo', '0009_remove_product_desc_remove_product_full_title_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
