# Generated by Django 5.0.2 on 2024-02-20 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('totembo', '0010_delete_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(upload_to='poster/', verbose_name='Фото для рекламы')),
                ('image2', models.ImageField(upload_to='poster/', verbose_name='Фото для рекламы')),
                ('image3', models.ImageField(upload_to='poster/', verbose_name='Фото для рекламы')),
            ],
            options={
                'verbose_name': 'Постер',
                'verbose_name_plural': 'Постеры',
            },
        ),
    ]
