# Generated by Django 5.0.2 on 2024-02-21 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('totembo', '0011_poster'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Poster',
        ),
    ]
