# Generated by Django 5.0.2 on 2024-02-21 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('totembo', '0012_delete_poster'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400, verbose_name='Краткоео описание к слайдеру')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images_slider/', verbose_name='Картинка для слайдера')),
            ],
            options={
                'verbose_name': 'Постер',
                'verbose_name_plural': 'Постеры',
            },
        ),
    ]
